### ISSUE TITLE
Enhancement - Improve rclone Speed

### ISSUE THREAD

**Issue by OneUnitedPowerValidator** [easy-node-one/validatortoolbox#37]
Saw this in the Harmony Discord, would be nice to add it to the Toolbox to achieve better rclone speeds. 

" Please add the following to your rclone command line to massively improve transfer speeds rclone -P -L sync release:pub.harmony.one/mainnet.min/harmony_db_0 harmony_db_0 --multi-thread-streams 8 --transfers=16 "

**Comment by patrickmogul** [comment]
branch is open, can someone test on a new server?

To get the branch pulled, perform a normal clone while configuring a new server, when you change into the toolbox directory to run pip3, also run this command as well:

`git pull https://github.com/easy-node-one/validatortoolbox.git feature/rclonemultithread`
